name: freq
description: "CSEN 268 Project."
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  flutter_bloc: ^8.1.5
  go_router: ^14.1.0
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  firebase_in_app_messaging: ^0.9.0+4
  firebase_messaging: ^16.0.4
  device_info_plus: ^12.2.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png