name: freq
description: "CSEN 268 Project."
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  flutter_bloc: ^8.1.5
  go_router: ^14.1.0
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  firebase_in_app_messaging: ^0.9.0+4
  firebase_messaging: ^16.0.4
  device_info_plus: ^10.0.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  equatable: ^2.0.7
  bloc: ^8.1.4
  firebase_core: ^4.2.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/splash1.png
    - assets/images/splash2.png
    - assets/images/splash3.png
    - assets/images/splash4.png
    - assets/images/splash5.png
    - assets/images/splash6.png
    - assets/images/splash7.png
    - assets/images/splash8.png
    - assets/images/splash9.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  