name: freq
description: "CSEN 268 Project."
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  flutter_bloc: ^8.1.5
  go_router: ^14.1.0   # For navigation
  equatable: ^2.0.5     # For value equality in Bloc states
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  just_audio: ^0.10.5
  audio_session: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png